@echo off

set FLASH_ATTENTION_TRITON_AMD_ENABLE=TRUE
set FLASH_ATTENTION_TRITON_AMD_AUTOTUNE=TRUE

set MIOPEN_FIND_MODE=2
set MIOPEN_LOG_LEVEL=3

set ZLUDA_COMGR_LOG_LEVEL=1

.\ZLUDA\zluda.exe -- %PYTHON% main.py %COMMANDLINE_ARGS%
pause